export class JsonData{

  jsonData ={

    "ShikeishoList": [
        {
          "shikeishoState": "BOM_APPROVED",
          "shikeisyoNo": "shno1",
          "shikeishoDescription": "Steering",
          "orderNo": "2212",
          "machineType": "engine",
          "rdDesiredDate": "2012-02-02",
          "dataOfIssue": "2018-01-02",
          "requestNo": "123",
          "productionVolumeUnits": "100",
          "payout1": "pay1",
          "payout2": "pay2",
          "payout3": "pay3",
          "requestCode": "plant1",
          "partsDestination": "ccd",
          "managementNo": "mngmentNo",
          "networkNumber": "net number",
          "materialCost": "$100",
          "designerName": "Balaji",
          "department": "abc",
          "group": "rd",
          "responsiblePersonL4": "john",
          "personInchrge": "tom",
          "remarks": "remarks",
          "eoNo": "eoNo",
          "requesterID": "vidhya",
          "parts": [
            {
              "PrototypeCode": "P",
              "district": "Bangalore",
              "generation": "gen",
              "partNumber": "partno",
              "partName": "partName",
              "quantity": "12",
              "internalDeliveryDate": "2018-01-02",
              "implementationInstruction": "instructions",
              "upg": "UPG",
              "interiorMakerName": "maker",
              "partRemarks": "part remark",
              "DrawingNo": "2334",
              "pps": "PPS",
              "status": "Order Placed",
              "dueDate": "12/04/2018",
              "deliverLocation": "del location",
              "DrawingUrl": "drawingurl.png"
            },
            {
              "PrototypeCode": "P",
              "district": "Bangalore",
              "generation": "gen",
              "partNumber": "partno2",
              "partName": "partName2",
              "quantity": "12",
              "internalDeliveryDate": "2018-01-02",
              "implementationInstruction": "instructions",
              "upg": "UPG",
              "interiorMakerName": "maker",
              "partRemarks": "part remark",
              "DrawingNo": "2334",
              "pps": "PPS",
              "status": "Order Placed",
              "dueDate": "12/04/2018",
              "deliverLocation": "del location",
              "DrawingUrl": "drawingurl.png"
            }
          ],
          "fundingApprovalLink": "https://www.ortusolis.com/logo.png"
        },
        {
          "shikeishoState": "LM_APPROVED",
          "shikeisyoNo": "shno",
          "shikeishoDescription": "Steering",
          "orderNo": "222",
          "machineType": "engine",
          "rdDesiredDate": "2012-02-02",
          "dataOfIssue": "2018-01-02",
          "requestNo": "123",
          "productionVolumeUnits": "100",
          "payout1": "pay1",
          "payout2": "pay2",
          "payout3": "pay3",
          "requestCode": "plant1",
          "partsDestination": "ccd",
          "managementNo": "mngmentNo",
          "networkNumber": "net number",
          "materialCost": "$100",
          "designerName": "Balaji",
          "department": "abc",
          "group": "rd",
          "responsiblePersonL4": "john",
          "personInchrge": "tom",
          "remarks": "remarks",
          "eoNo": "eoNo",
          "requesterID": "vidhya",
          "parts": [
            {
              "PrototypeCode": "P",
              "district": "Bangalore",
              "generation": "gen",
              "partNumber": "partno",
              "partName": "partName",
              "quantity": "12",
              "internalDeliveryDate": "2018-01-02",
              "implementationInstruction": "instructions",
              "upg": "UPG",
              "interiorMakerName": "maker",
              "partRemarks": "part remark",
              "DrawingNo": "2334",
              "pps": "PPS",
              "status": "Order Placed",
              "dueDate": "12/04/2018",
              "deliverLocation": "del location",
              "DrawingUrl": "drawingurl.png"
            },
            {
              "PrototypeCode": "P",
              "district": "Bangalore",
              "generation": "gen",
              "partNumber": "partno2",
              "partName": "partName2",
              "quantity": "12",
              "internalDeliveryDate": "2018-01-02",
              "implementationInstruction": "instructions",
              "upg": "UPG",
              "interiorMakerName": "maker",
              "partRemarks": "part remark",
              "DrawingNo": "2334",
              "pps": "PPS",
              "status": "Order Placed",
              "dueDate": "12/04/2018",
              "deliverLocation": "del location",
              "DrawingUrl": "drawingurl.png"
            }
          ],
          "fundingApprovalLink": "https://www.ortusolis.com/logo.png"
        }
      ]
    }
    
  } 
